language: rust
rust:
  - nightly

cache:
  cargo: true
  directories:
    - edit-frontend/node_modules/

addons:
  firefox: "latest"

node_js: 
  - "stable"

branches:
  only:
    # Don't auto build pull requests.
    # - master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    
    # Greenkeeper
    - /^greenkeeper/.*$/

before_install:
  # Get access to origin/ branches
  # https://stackoverflow.com/a/47441734/6728025
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags

  # Test node version
  - node -v
  
  # Test Rust version
  # - A daily cron job tests the latest nightly, to keep a running track record
  #   of which nightly versions the repo is compatible without modification.
  - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then echo 'nightly' > rust-toolchain; fi
  - rustc -V
  
  # Install geckodriver 0.23
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  # Prepare X service
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait to start

  # Run test
  - ./tools ci

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs/book/
  on:
    branch: staging
