# Based on https://github.com/starkat99/appveyor-rust

# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2015

branches:
  only:
    # Enable building pull requests.
    #- master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying

environment:
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc

  # Stable 32-bit MSVC
  #  - channel: stable
  #    target: i686-pc-windows-msvc

cache:
  - '%USERPROFILE%\.cargo'
  - '%USERPROFILE%\.rustup'
  - 'edit-frontend\node_modules'

# Install Script

install:
  # Install Node.js
  - ps: Install-Product node ''

  # Install rustup
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

# Test Script

# 'cargo test' takes care of building for us, so disable Appveyor's build stage.
# This prevents the "directory does not contain a project or solution file" error.
build: false

test_script:
- .\tools ci
